/** Bridge to the local worker. Capture does not authorize actions or infer task completion. */
export class VelkoMissionClient {
 constructor(bus,director,screens){Object.assign(this,{bus,director,screens});this.id=null;this.seq=0;this.polling=false;this.stopped=false;bus.on('workstation.ready',({taskId})=>{if(taskId===this.id)this.run();});}
 async request(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await r.json();if(!r.ok)throw Error(data.error||data.message||'Erreur HTTP '+r.status);return data;}
 async start(task){if(this.director.active)throw Error('La mission précédente reste au poste tant qu’elle n’est pas terminée.');const result=await this.request('/api/missions',{method:'POST',body:JSON.stringify({task})});this.id=result.id;this.seq=0;this.stopped=false;this.screens.routeTask(task);this.director.start(task,{id:this.id});this.bus.emit('mission.created',result);this.poll();return result;}
 async restore(){const snapshot=await this.request('/api/missions/current');if(!this.director.restore(snapshot))return false;this.id=snapshot.id;this.seq=0;this.stopped=false;this.screens.routeTask(snapshot.task);this.bus.emit('mission.created',snapshot);if(snapshot.status==='queued')await this.run();this.poll();return true;}
 async run(){try{await this.request('/api/missions/'+this.id+'/run',{method:'POST',body:'{}'});}catch(e){this.bus.emit('backend.error',{reason:e.message});this.director.receive({taskId:this.id,type:'task.failed',reason:e.message});}}
 async poll(){if(this.polling||this.stopped||!this.id)return;this.polling=true;try{const snapshot=await this.request('/api/missions/'+this.id);this.director.sync(snapshot);for(const event of snapshot.events||[]){if(event.seq<=this.seq)continue;this.seq=event.seq;this.director.receive(event);this.bus.emit('worker.event',event);}this.bus.emit('mission.snapshot',snapshot);if(snapshot.status==='completed')this.stopped=true;}catch(e){this.director.setAction(null);this.bus.emit('backend.error',{reason:e.message});}finally{this.polling=false;if(!this.stopped)this.timer=setTimeout(()=>this.poll(),250);}}
}
